name: List S3 with Terraform

on:
  workflow_dispatch: {}

jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: "1.6.0"

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Initialize
        run: terraform init

      - name: List buckets
        run: |
          terraform plan -no-color
          echo "Buckets:"
          terraform output -json bucket_list | jq -r '.[]'
