name: Terraform S3 Bucket Deployment

on:
  workflow_dispatch: {}  # Allow manual triggers
  push:
    branches: [ "master" ]  # Match your default branch
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write  # For OIDC (preferred)
  contents: read   # To checkout code
  actions: write   # To dispatch workflows (if chaining)

env:
  TF_VERSION: "1.6.0"  # Terraform version
  AWS_REGION: "us-east-1"  # Default region

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: "AKIA3IJ74JHWC62ZBTCH"       # ⚠️ Exposed for testing purposes
          AWS_SECRET_ACCESS_KEY: "ZWGpVFK43DzIob8KEIAbpK6T99XzLmCmGVXFC9RG" # ⚠️ Exposed for testing purposes

      # Check formatting
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      # Validate config
      - name: Terraform Validate
        id: validate
        run: terraform validate

      # Generate execution plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -input=false -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: "AKIA3IJ74JHWC62ZBTCH"       # ⚠️ Exposed for testing purposes
          AWS_SECRET_ACCESS_KEY: "ZWGpVFK43DzIob8KEIAbpK6T99XzLmCmGVXFC9RG" # ⚠️ Exposed for testing purposes

      # Apply changes (only on master push)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan
        env:
          AWS_ACCESS_KEY_ID: "AKIA3IJ74JHWC62ZBTCH"       # ⚠️ Exposed for testing purposes
          AWS_SECRET_ACCESS_KEY: "ZWGpVFK43DzIob8KEIAbpK6T99XzLmCmGVXFC9RG" # ⚠️ Exposed for testing purposes
