apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${values.component_id}
  description: S3 Bucket created via Terraform
  annotations:
    github.com/project-slug: ${values.repo_url | replace('https://github.com/', '')}
    backstage.io/techdocs-ref: dir:.
spec:
  type: infrastructure
  lifecycle: production
  owner: user:guest
