apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: NarendraJatti/backstage-software-templates
    github.com/actions-workflows: 's3-terraform'  # Name of your workflow file
    backstage.io/source-location: url:https://github.com/NarendraJatti/backstage-software-templates/tree/main/
spec:
  type: infrastructure
  lifecycle: production
  owner: user:guest
