site_name: 'Python-app'
site_description: 'Main documentation for 'Python-app''
repo_url: https://github.com/backstage/backstage
edit_uri: edit/master/docs

plugins:
  - techdocs-core


# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started!: 'docs/index.md'   
