site_name: Python-app  # Quotes not needed for simple values
site_description: Main documentation for Python-app  # Fixed quote nesting
repo_url: https://github.com/backstage/backstage
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started!: docs/index.md  # Fixed indentation and quotes
